import React from 'react';

export function About() {
    return (
            <div>
                Lorem ipsum dolor sit amet consectetur, adipisicing elit. Optio iure quibusdam voluptates exercitationem quae dolore nihil laborum illo at eveniet asperiores dignissimos, nam similique eius distinctio accusamus nisi impedit vitae delectus eaque voluptatibus? Adipisci explicabo esse labore iusto eaque ullam, doloribus consequuntur mollitia obcaecati provident possimus omnis, dolorum quaerat quis veniam atque. Minus, tenetur ipsam. Molestias, cumque pariatur porro eligendi et veritatis? Corrupti asperiores reprehenderit distinctio excepturi voluptatem nam cum ea ratione quaerat, eum dolorum sit ipsa molestiae explicabo earum! Reiciendis similique itaque iusto facilis unde id ipsam exercitationem quod hic laborum perferendis deleniti, quis perspiciatis animi laudantium vitae, assumenda quaerat iure dicta dolorem? Atque, animi quidem? Repudiandae rem, aperiam ad sapiente aliquam nemo fugiat temporibus nulla ea! Hic libero amet voluptate tenetur blanditiis nulla reprehenderit esse iste ducimus modi incidunt culpa, minima quibusdam quos quia soluta facere tempora, veniam magnam vitae voluptatem eum. Incidunt, omnis et eum exercitationem perferendis quidem rem officiis voluptate odio delectus, quod doloribus inventore. Accusantium doloribus molestiae assumenda perferendis voluptatum at laboriosam tenetur rerum, non, magnam, voluptatibus hic natus atque sint. Tempore laboriosam voluptate, dolorum molestiae eos, tenetur magnam amet culpa molestias, tempora est placeat hic ullam et officiis. Consequatur, nam ab? Sint facilis asperiores vitae voluptas animi magnam qui aspernatur velit, temporibus ad architecto ab dolore accusamus quos distinctio veniam nihil eligendi consequuntur. Exercitationem illum quis suscipit tempora repudiandae placeat fugiat expedita, sed distinctio consequatur possimus quas blanditiis doloribus aliquam sapiente veritatis necessitatibus. Distinctio, laboriosam deleniti labore est autem culpa recusandae non ea, sed quis nisi. Ducimus nostrum in pariatur deleniti sequi rerum esse quis nam neque deserunt obcaecati exercitationem corrupti tempora iste sint, quas quam voluptatem vero sapiente laboriosam consequatur? Vel excepturi temporibus quis, laudantium tenetur ipsa libero est, qui voluptatem fugiat commodi doloribus? Id ducimus voluptatibus quae minima assumenda saepe voluptates natus quisquam sapiente cum nesciunt officia numquam quis ratione cupiditate soluta ipsam delectus reiciendis, ab eveniet dolorem placeat. Ab ipsum aut quo, fuga, qui animi cumque porro ea nobis tempora culpa.
            </div>
        );
}
